<?php

namespace Database\Seeders;

use App\Models\BankSampah;
use Illuminate\Database\Seeder;

class BankSampahSeeder extends Seeder
{
    public function run(): void
    {
        $units = [
            [
                'kode_bank' => 'BS-001',
                'nama' => 'Bank Sampah Melati Bersih',
                'slug' => 'bank-sampah-melati-bersih',
                'deskripsi' => 'Unit pusat pengelolaan daur ulang sampah organik dan anorganik wilayah Bandung Tengah.',
                'email' => 'melati.bersih@sisampah.id',
                'telepon' => '081234567890',
                'whatsapp' => '6281234567890',
                'website' => 'https://melatibersih.sisampah.id',
                'alamat' => 'Jl. Ir. H. Juanda No. 123, Dago, Kec. Coblong, Kota Bandung, Jawa Barat',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Kota Bandung',
                'kecamatan' => 'Coblong',
                'desa' => 'Dago',
                'kode_pos' => '40135',
                'latitude' => -6.8915,
                'longitude' => 107.6107,
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'hari_operasional' => 'Senin - Sabtu',
                'radius_layanan' => 2000,
                'status' => 'aktif',
            ],
            [
                'kode_bank' => 'BS-002',
                'nama' => 'Bank Sampah Tampingan Asri',
                'slug' => 'bank-sampah-tampingan-asri',
                'deskripsi' => 'Spesialis daur ulang plastik PET, HDPE, dan minyak jelantah terpadu.',
                'email' => 'tampingan.asri@sisampah.id',
                'telepon' => '081298765432',
                'whatsapp' => '6281298765432',
                'website' => 'https://tampinganasri.sisampah.id',
                'alamat' => 'Jl. Tampingan Utama No. 45, Kec. Boja, Kab. Kendal, Jawa Tengah',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Kendal',
                'kecamatan' => 'Boja',
                'desa' => 'Tampingan',
                'kode_pos' => '51381',
                'latitude' => -7.0911,
                'longitude' => 110.2711,
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'hari_operasional' => 'Senin - Sabtu',
                'radius_layanan' => 2000,
                'status' => 'aktif',
            ],
            [
                'kode_bank' => 'BS-003',
                'nama' => 'Bank Sampah Kenanga Utama',
                'slug' => 'bank-sampah-kenanga-utama',
                'deskripsi' => 'Unit penerima sampah elektronik, logam, dan minyak jelantah.',
                'email' => 'kenanga.utama@sisampah.id',
                'telepon' => '081311223344',
                'whatsapp' => '6281311223344',
                'website' => 'https://kenangautama.sisampah.id',
                'alamat' => 'Jl. Soekarno-Hatta No. 450, Kec. Batununggal, Kota Bandung, Jawa Barat',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Kota Bandung',
                'kecamatan' => 'Batununggal',
                'desa' => 'Mengger',
                'kode_pos' => '40267',
                'latitude' => -6.9450,
                'longitude' => 107.6320,
                'jam_buka' => '09:00',
                'jam_tutup' => '17:00',
                'hari_operasional' => 'Senin - Sabtu',
                'radius_layanan' => 2000,
                'status' => 'aktif',
            ],
            [
                'kode_bank' => 'BS-004',
                'nama' => 'Bank Sampah Surabaya Eco',
                'slug' => 'bank-sampah-surabaya-eco',
                'deskripsi' => 'Unit ramah lingkungan pengelolaan daur ulang anorganik Kota Surabaya.',
                'email' => 'surabaya.eco@sisampah.id',
                'telepon' => '081455667788',
                'whatsapp' => '6281455667788',
                'website' => 'https://surabayaeco.sisampah.id',
                'alamat' => 'Jl. Raya Darmo No. 12, Tegalsari, Kota Surabaya, Jawa Timur',
                'provinsi' => 'Jawa Timur',
                'kabupaten' => 'Kota Surabaya',
                'kecamatan' => 'Tegalsari',
                'desa' => 'Dr. Soetomo',
                'kode_pos' => '60264',
                'latitude' => -7.2891,
                'longitude' => 112.7388,
                'jam_buka' => '08:00',
                'jam_tutup' => '15:30',
                'hari_operasional' => 'Senin - Jumat',
                'radius_layanan' => 2000,
                'status' => 'aktif',
            ],
            [
                'kode_bank' => 'BS-005',
                'nama' => 'Bank Sampah Bali Asri',
                'slug' => 'bank-sampah-bali-asri',
                'deskripsi' => 'Pengelolaan limbah botol kaca, aluminium, dan plastik wilayah Denpasar.',
                'email' => 'bali.asri@sisampah.id',
                'telepon' => '081599887766',
                'whatsapp' => '6281599887766',
                'website' => 'https://baliasri.sisampah.id',
                'alamat' => 'Jl. Teuku Umar No. 88, Denpasar Barat, Kota Denpasar, Bali',
                'provinsi' => 'Bali',
                'kabupaten' => 'Kota Denpasar',
                'kecamatan' => 'Denpasar Barat',
                'desa' => 'Dauh Puri',
                'kode_pos' => '80113',
                'latitude' => -8.6705,
                'longitude' => 115.2126,
                'jam_buka' => '08:30',
                'jam_tutup' => '16:30',
                'hari_operasional' => 'Senin - Sabtu',
                'radius_layanan' => 2000,
                'status' => 'aktif',
            ],
        ];

        foreach ($units as $unit) {
            BankSampah::updateOrCreate(['kode_bank' => $unit['kode_bank']], $unit);
        }

        BankSampah::query()->update(['radius_layanan' => 2000]);
    }
}
