<?php

namespace Database\Seeders;

use App\Models\TrashCategory;
use Illuminate\Database\Seeder;

class TrashCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'nama' => 'Plastik',
                'kode' => 'PLS-001',
                'kategori' => 'anorganik',
                'jenis' => 'Botol PET, Kantong, Kemasan',
                'gambar' => 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=600&q=80',
                'harga_per_kg' => 3500,
                'harga_per_gram' => 3.5000,
                'satuan' => 'kg',
                'kualitas' => 'standar',
                'stok_dibutuhkan' => 500,
                'status_harga' => 'naik',
                'perubahan_persen' => 5.50,
                'deskripsi' => 'Sampah plastik termasuk botol, kantong, dan kemasan plastik lainnya',
                'manfaat' => 'Plastik daur ulang dapat dijadikan biji plastik untuk industri manufaktur, mengurangi ketergantungan terhadap plastik baru dari minyak bumi.',
                'nilai_daur_ulang' => 'Tinggi',
                'tips_penyimpanan' => 'Cuci bersih, lepaskan label, kempiskan botol agar hemat tempat. Simpan di tempat kering.',
                'tips_menjual' => 'Pilah berdasarkan jenis plastik (PET, HDPE, PP). Plastik bersih dan terpilah mendapat harga lebih tinggi.',
                'is_archived' => false,
            ],
            [
                'nama' => 'Kardus',
                'kode' => 'KDS-001',
                'kategori' => 'anorganik',
                'jenis' => 'Kardus Bekas, Box Kemasan',
                'gambar' => 'https://images.unsplash.com/photo-1607166452427-7e4477c2c9b0?w=600&q=80',
                'harga_per_kg' => 2500,
                'harga_per_gram' => 2.5000,
                'satuan' => 'kg',
                'kualitas' => 'standar',
                'stok_dibutuhkan' => 300,
                'status_harga' => 'stabil',
                'perubahan_persen' => 0,
                'deskripsi' => 'Kardus bekas dan kertas kemasan',
                'manfaat' => 'Kardus daur ulang menjadi kertas baru, mengurangi penebangan pohon dan konsumsi air dalam proses produksi kertas.',
                'nilai_daur_ulang' => 'Tinggi',
                'tips_penyimpanan' => 'Lipat rapi, hindari basah. Pisahkan dari kardus berlapis plastik atau aluminium.',
                'tips_menjual' => 'Kardus yang bersih dan kering mendapat harga terbaik. Ikat rapi dalam bundel.',
                'is_archived' => false,
            ],
            [
                'nama' => 'Kertas',
                'kode' => 'KRT-001',
                'kategori' => 'anorganik',
                'jenis' => 'Kertas HVS, Koran, Majalah',
                'gambar' => 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&q=80',
                'harga_per_kg' => 2000,
                'harga_per_gram' => 2.0000,
                'satuan' => 'kg',
                'kualitas' => 'standar',
                'stok_dibutuhkan' => 400,
                'status_harga' => 'turun',
                'perubahan_persen' => -2.30,
                'deskripsi' => 'Kertas putih, koran, dan majalah',
                'manfaat' => 'Kertas daur ulang menghemat 70% energi dibandingkan membuat kertas baru. Mengurangi sampah di TPA.',
                'nilai_daur_ulang' => 'Sedang',
                'tips_penyimpanan' => 'Simpan di tempat kering, jauhkan dari air. Pisahkan kertas putih dari koran.',
                'tips_menjual' => 'Kertas putih HVS dihargai lebih tinggi dari koran. Jangan campur dengan kertas basah.',
                'is_archived' => false,
            ],
            [
                'nama' => 'Logam',
                'kode' => 'LGM-001',
                'kategori' => 'anorganik',
                'jenis' => 'Aluminium, Besi, Tembaga',
                'gambar' => 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80',
                'harga_per_kg' => 8000,
                'harga_per_gram' => 8.0000,
                'satuan' => 'kg',
                'kualitas' => 'premium',
                'stok_dibutuhkan' => 200,
                'status_harga' => 'naik',
                'perubahan_persen' => 8.75,
                'deskripsi' => 'Logam bekas termasuk aluminium, besi, dan tembaga',
                'manfaat' => 'Logam 100% dapat didaur ulang tanpa kehilangan kualitas. Menghemat 95% energi dibanding menambang baru.',
                'nilai_daur_ulang' => 'Sangat Tinggi',
                'tips_penyimpanan' => 'Pisahkan berdasarkan jenis logam. Hindari logam berkarat tercampur dengan yang bersih.',
                'tips_menjual' => 'Tembaga dan aluminium memiliki nilai tertinggi. Pisahkan dari besi untuk harga optimal.',
                'is_archived' => false,
            ],
            [
                'nama' => 'Kaca',
                'kode' => 'KCC-001',
                'kategori' => 'anorganik',
                'jenis' => 'Botol Kaca, Pecahan Aman',
                'gambar' => 'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&q=80',
                'harga_per_kg' => 1500,
                'harga_per_gram' => 1.5000,
                'satuan' => 'kg',
                'kualitas' => 'standar',
                'stok_dibutuhkan' => 150,
                'status_harga' => 'stabil',
                'perubahan_persen' => 0,
                'deskripsi' => 'Botol kaca dan pecahan kaca yang aman',
                'manfaat' => 'Kaca dapat didaur ulang berkali-kali tanpa penurunan kualitas. Mengurangi penggunaan pasir silika.',
                'nilai_daur_ulang' => 'Tinggi',
                'tips_penyimpanan' => 'Bungkus pecahan kaca dengan koran. Simpan botol utuh terpisah dari pecahan.',
                'tips_menjual' => 'Botol utuh lebih bernilai dari pecahan. Pisahkan berdasarkan warna kaca.',
                'is_archived' => false,
            ],
            [
                'nama' => 'Organik',
                'kode' => 'ORG-001',
                'kategori' => 'organik',
                'jenis' => 'Sisa Makanan, Daun, Ranting',
                'gambar' => 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80',
                'harga_per_kg' => 500,
                'harga_per_gram' => 0.5000,
                'satuan' => 'kg',
                'kualitas' => 'rendah',
                'stok_dibutuhkan' => 1000,
                'status_harga' => 'stabil',
                'perubahan_persen' => 0,
                'deskripsi' => 'Sampah organik seperti sisa makanan dan daun',
                'manfaat' => 'Dijadikan kompos berkualitas untuk pertanian organik. Mengurangi emisi metana dari TPA.',
                'nilai_daur_ulang' => 'Sedang',
                'tips_penyimpanan' => 'Pisahkan dari sampah anorganik. Gunakan wadah tertutup untuk menghindari bau.',
                'tips_menjual' => 'Sampah organik segar lebih disukai untuk komposting. Hindari mencampur dengan sampah berminyak.',
                'is_archived' => false,
            ],
            [
                'nama' => 'Elektronik',
                'kode' => 'ELK-001',
                'kategori' => 'b3',
                'jenis' => 'PCB, Kabel, Komponen',
                'gambar' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
                'harga_per_kg' => 12000,
                'harga_per_gram' => 12.0000,
                'satuan' => 'kg',
                'kualitas' => 'premium',
                'stok_dibutuhkan' => 50,
                'status_harga' => 'naik',
                'perubahan_persen' => 12.00,
                'deskripsi' => 'Limbah elektronik termasuk PCB, kabel, dan komponen elektronik',
                'manfaat' => 'Mengandung logam mulia (emas, perak, tembaga). Mendukung urban mining dan mengurangi pencemaran lingkungan.',
                'nilai_daur_ulang' => 'Sangat Tinggi',
                'tips_penyimpanan' => 'Jangan bongkar baterai. Simpan di tempat kering, jauhkan dari jangkauan anak.',
                'tips_menjual' => 'Peralatan utuh lebih bernilai. Pisahkan kabel tembaga dari komponen PCB.',
                'is_archived' => false,
            ],
            [
                'nama' => 'Minyak Jelantah',
                'kode' => 'MJL-001',
                'kategori' => 'organik',
                'jenis' => 'Minyak Goreng Bekas',
                'gambar' => 'https://images.unsplash.com/photo-1474979266404-7f28db3f3c49?w=600&q=80',
                'harga_per_kg' => 4000,
                'harga_per_gram' => 4.0000,
                'satuan' => 'kg',
                'kualitas' => 'standar',
                'stok_dibutuhkan' => 100,
                'status_harga' => 'naik',
                'perubahan_persen' => 3.20,
                'deskripsi' => 'Minyak goreng bekas pakai yang sudah disaring',
                'manfaat' => 'Diolah menjadi biodiesel ramah lingkungan. Mengurangi pencemaran air dari pembuangan minyak sembarangan.',
                'nilai_daur_ulang' => 'Tinggi',
                'tips_penyimpanan' => 'Saring dari sisa makanan, simpan dalam botol tertutup rapat.',
                'tips_menjual' => 'Minyak yang bersih dari ampas mendapat harga lebih baik. Kumpulkan minimal 5 liter.',
                'is_archived' => false,
            ],
        ];

        foreach ($categories as $category) {
            TrashCategory::updateOrCreate(
                ['kode' => $category['kode']],
                $category
            );
        }
    }
}
